### ISSUE TITLE
容器启动后在登录界面登录控制台提示“数据库链接错误" is not valid JSON

### ISSUE THREAD

**Issue by Haruter** [lkw199711/smanga#1]
报错信息：SyntaxError: Unexpected token '数', "数据库链接错误" is not valid JSON

**Comment by lkw199711** [comment]
1."数据库链接错误", 为映射的mysql目录没有权限, 使得数据库文件没有正常写入, 镜像内使用用户uid为1000, 请确保宿主机也有1000的用户, 否则将会出现权限问题无法读取数据库与解压文件

2.如果使用的是群晖系统,uid默认为1026, 请使用群晖版的docker镜像, lkw199711/smanga:synology

3.如果只是想简单试用或调试,可将三个目录都不映射, 能够摆脱权限问题正常运行. 但是升级或是重建镜像 数据会丢失

**Comment by Haruter** [comment]
问题解决，因系统环境为centos7 默认不存在1000uid账户，且使用centos默认仓库安装的docker会出现问题，暂无深究，建议根据docker官方文档进行安装；且自建映射目录分配777权限后，项目方可正常运行。
