### ISSUE TITLE
群晖版无法处理7z格式的漫画压缩包

### ISSUE THREAD

**Issue by mafuyukoi** [lkw199711/smanga#10]
![image](https://user-images.githubusercontent.com/104770534/220806223-6df878e4-fa71-4598-97ee-7460a0edb2fa.png)
添加7z格式的压缩包，打开漫画时会提示正在进行压缩转换并在compress创建相应文件夹，但是文件夹内容为空。但是先把7z格式的压缩包解压再压缩为zip/rar格式就能正常转换观看。
顺便问一下 压缩管理和漫画管理有意向添加搜索吗

感谢大大的奉献

**Comment by lkw199711** [comment]
请携带版本号， 在使用说明（wiki）界面。

**Comment by mafuyukoi** [comment]
![image](https://user-images.githubusercontent.com/104770534/220850401-09f13887-9c43-45c0-991d-685410de2c76.png)
![image](https://user-images.githubusercontent.com/104770534/220850410-6034a81d-b117-4082-8ba8-90b7a7d6404a.png)
拉取镜像选的是 lkw199711/smanga:synology

**Comment by mafuyukoi** [comment]
> 请携带版本号， 在使用说明（wiki）界面。
![image](https://user-images.githubusercontent.com/104770534/220850401-09f13887-9c43-45c0-991d-685410de2c76.png)
![image](https://user-images.githubusercontent.com/104770534/220850410-6034a81d-b117-4082-8ba8-90b7a7d6404a.png)
拉取镜像选的是 lkw199711/smanga:synology

**Comment by mafuyukoi** [comment]
> 请携带版本号， 在使用说明（wiki）界面。

![image](https://user-images.githubusercontent.com/104770534/220850401-09f13887-9c43-45c0-991d-685410de2c76.png)
![image](https://user-images.githubusercontent.com/104770534/220850410-6034a81d-b117-4082-8ba8-90b7a7d6404a.png)
拉取镜像选的是 lkw199711/smanga:synology

**Comment by lkw199711** [comment]
关于7z的支持 已在最新的beta版本修复, 请更换镜像使用"lkw99711/smanga:beta", (群晖添加参数PUID=1026 或 0)
目前由于数据库结构的原因,无法通过升级修复此问题,请删除数据后重新部署最新beta. 如果您不想丢失数据, 请手动此修复数据库, 将compress表中的compressType的枚举值新增'7z', 然后升级镜像
![3 1 4](https://user-images.githubusercontent.com/38646029/221727059-b735a498-ea32-4c2b-8e1e-65d3a51ccceb.PNG)
