### ISSUE TITLE
支持格式

### ISSUE THREAD

**Issue by Billy0220** [lkw199711/smanga#104]
想知道smanga支不支持epub格式

**Comment by lkw199711** [comment]
仅支持图片文件,我发识别小说

**Comment by Billy0220** [comment]
那 要是我有两个不同类型的媒体库 但是都是扫描同一个目录的 会有冲突吗
lkw199711 wrote:
仅支持图片文件,我发识别小说

**Comment by lkw199711** [comment]
会按漫画识别出来,只展示图片, 扫完删掉即可,应该是不太影响
