### ISSUE TITLE
请修改收藏

### ISSUE THREAD

**Issue by SAENE** [lkw199711/smanga#108]
目前收藏漫画书只能有一本，如果在想收藏，则数据库不让写入。
原因是章节id
[![pCXpYid.png](https://s1.ax1x.com/2023/07/25/pCXpYid.png)](https://imgse.com/i/pCXpYid)
收藏漫画书默认章节id为-1，接下的收藏的漫画书章节id默认也为-1冲突了，所有收藏不了
[![pCXptJA.png](https://s1.ax1x.com/2023/07/25/pCXptJA.png)](https://imgse.com/i/pCXptJA)

**Comment by lkw199711** [comment]
收到

**Comment by lkw199711** [comment]
方便发一下版本号吗, 我用最新版的beta测试没有问题.

**Comment by SAENE** [comment]
额，破案了,我用的docker latest标签，貌似latest标签一直没更新啊

**Comment by lkw199711** [comment]
请谨慎升级,beta版本问题较多,正在修复中
