### ISSUE TITLE
在3.3.5和beta中部分文件权限问题和根目录访问404

### ISSUE THREAD

**Issue by SAENE** [lkw199711/smanga#110]
在3.3.5和beta中部分文件权限问题和根目录访问404问题
1. 如果使用puid和pgid参数会遇到
     PermissionError: [Errno 13] Permission denied: '/logs/supervisord.log'
      解决办法是改权限
2. 不知道是不是故意为之，在/etc/nginx/conf.d中的配置文件设置根目录为/app，但网站文件在/app/docker里，所以访问得加个/docker路径。
     可以试试在配置里 location /里设置root根目录

**Comment by DDSDerek** [comment]
感谢反馈，第一个问题已经解决，第二个问题最新beta版本未发现。
