### ISSUE TITLE
使用一段时间后对于smanga的建议和所遇到的问题

### ISSUE THREAD

**Issue by MYJN** [lkw199711/smanga#115]
建议:
------
* 1. 对于媒体库功能选项:媒体库类型、默认浏览方式、默认浏览方式、文件夹机构,增加对应释义说明和示例,切换不同选项时显示不同功能说明和示例
* 2. 标签管理> 新增标签>标签颜色, 希望能增加色表选择功能
* 3. 新增NAS上动漫文件管理功能
* 4. 希望能新增漫画信息刮削功能及自动添加TAG保存至对应的nfo文件中，smanga自动读取nfo 加快漫画信息添加完善漫画信息,（对于漫画信息数据完善速度及管理，个人更偏向于nfo文件方式）
------
问题:
------
* 1. 切换媒体库时出现数据延迟刷新，切换到另一个B媒体库时出现A媒体库信息，3秒之后显示信息才刷新
* 2. 在A媒体库点开漫画之后，切换到B媒体库点开漫画，出现A媒体库点开的内容，等一会才刷新到A媒体库的漫画内容
* 3. 漫画已点开浏览过，切换回漫画列表，漫画封面未刷新，重新进去媒体库漫画封面也未刷新
* 4. 漫画封面遇到横屏图时，能不能进行自定义裁切或者图片自动缩放

**Comment by lkw199711** [comment]
感谢反馈,这些问题具体解决方案还需再研究,请留意后续更新
