### ISSUE TITLE
请问元数据从哪里拉取？

### ISSUE THREAD

**Issue by 2640123** [lkw199711/smanga#124]
请问可以从https://bangumi.tv/拉元数据吗？

**Comment by lkw199711** [comment]
目前进提供了特定元数据格式,如果用户自有元数据格式需要支持,可以发出来. 我会在后些版本更新

**Comment by lkw199711** [comment]
我目前对于这个事情的态度是,我不会因为一句可否支持某某网站而去做研究,因为我自己并不是这些网站的用户.
但是如果你自身拥有很多来自这个网站的元数据,可以发给我一些示例,smanga将对其做支持
