### ISSUE TITLE
能不能别往docker日志输出进程守护的信息

### ISSUE THREAD

**Issue by SAENE** [lkw199711/smanga#169]
[![pi3B3tg.png](https://z1.ax1x.com/2023/11/09/pi3B3tg.png)](https://imgse.com/i/pi3B3tg)
多少有点蚌住了，几小时没看，如果没设置日志文件大小，迟早存储消耗没
我用的 lkw199711/smanga:nosql-3.6.0，因为显示在改文件所有权，所以没管，几小时后想想差不多，就过来看看，结果一堆日志

**Comment by lkw199711** [comment]
1
