### ISSUE TITLE
部分zip内容无法正常解压读取

### ISSUE THREAD

**Issue by Kirrito-k423** [lkw199711/smanga#174]
# 问题描述

部分zip文件，点击“开始阅读”，会报错`Undefined variable: sqlList`
![image](https://github.com/lkw199711/smanga/assets/44373239/a4c432d8-43a7-4e44-a997-44c0141a0e20)

## komga 可以正常读取 

![image](https://github.com/lkw199711/smanga/assets/44373239/2ad4df19-88ff-4793-b9aa-f35c0bac7552)

祝好！

**Comment by lkw199711** [comment]
![image](https://github.com/lkw199711/smanga/assets/38646029/ed3991fe-5994-49be-ab44-59548f3b1c38)
建议查看媒体库设置,确认单本选项.
确认smanga版本是否为最新(近几个版本扫描无问题)
然后smanga自3.5.1之后会自动提取压缩包中的封面,但是我看你的贴图是没有展示封面的,我认为你的扫描任务没有执行成功

**Comment by Kirrito-k423** [comment]
确实不是bug，我更改了单本选项就好了，谢谢。
