### ISSUE TITLE
功能：PDF阅读与decompress任务的优先级问题

### ISSUE THREAD

**Issue by Kirrito-k423** [lkw199711/smanga#175]
# 问题描述

我再添加了一个zip包的大库之后，会打不开pdf。看图是要等待转换完成？

![image](https://github.com/lkw199711/smanga/assets/44373239/6570fcf9-2a0f-4025-95d3-d57ef2e907a3)

我确实观察到有正在进行的decompress任务

![image](https://github.com/lkw199711/smanga/assets/44373239/5644f0ca-8705-4722-a8df-605ace10dd2b)

# 建议

我想这个PDF阅读的优先级，能不能提高到decompress的前面，应该会有利于阅读，谢谢。

**Comment by lkw199711** [comment]
解压任务都是同级别的，不能够设置优先级。另外不太推荐开启自动解压功能，下个版本准备退出解压文件自动清理逻辑。

**Comment by Kirrito-k423** [comment]
我检查了我的设置，发现”自动解压功能“是关闭的。Whatever，等了两天，好像就都解压好了。能正常观看了。
