### ISSUE TITLE
问题：PDF格式文件 的组织、读取

### ISSUE THREAD

**Issue by Kirrito-k423** [lkw199711/smanga#176]
# 赞美

经过一段时间的使用，作者对于zip和 png的格式处理，十分不错，能正常使用。

# 困惑

在文件结构的选择时，并没有写存放pdf文件的内容如何组织。

比如下图，我应该把单个pdf文件当作选项中的图片还是章节，还是应该每个pdf用一个同名文件夹重新包裹。

![image](https://github.com/lkw199711/smanga/assets/44373239/56eb5279-ca32-44d5-90cf-52321035ae69)

# 问题描述

在pdf 文件转换时，也有打不开的问题。（当然我暂时不知道是不是前面路径的问题。）

![image](https://github.com/lkw199711/smanga/assets/44373239/7e586323-caff-4966-b4e9-c10001077131)

查看转换的信息，貌似转换失败了：

![image](https://github.com/lkw199711/smanga/assets/44373239/fa9a0b23-c197-4688-b614-608487d5a963)

# 期待

**如果能完善pdf的相关功能，smanga离最好的阅读器又更进一步**，祝好

**Comment by lkw199711** [comment]
pdf与zip同目录类型，不需要另外单独的处理。如果解压失败可能是cpu性能不足。请查看smanga更新公告，尝试调整参数。（pdf解压推荐使用八核心以上桌面级cpu）

**Comment by Kirrito-k423** [comment]
理解了，正确设置后。等了一天后，就能正常现实了。Tks.
