### ISSUE TITLE
希望媒体库能够根据文件夹的目录结构显示多层文件夹

### ISSUE THREAD

**Issue by nobel2377** [lkw199711/smanga#182]
例如我的文件夹目录结构是
--合集
----a合集
------第n话
--------xxxx.jpg

现在好像是只能在合集这个媒体库里把所有话的文件夹都显示出来，不会显示“a合集”这个文件夹，这样的话媒体库显示出来的内容有点难寻找和选择。我现在的解决办法是把“a合集”单独出来一个媒体库，不过把每个合集都添加到媒体库感觉有点麻烦....
不知道有没有办法实现（

**Comment by lkw199711** [comment]
已于3.6.7版本处理,,使用了简单粗暴的方式,现在点击会展示二级目录,但是需要重新扫描
![image](https://github.com/lkw199711/smanga/assets/38646029/a48c95bc-1ded-4495-8eca-d05cf8d22d6a)
