### ISSUE TITLE
希望能使排序功能持久化

### ISSUE THREAD

**Issue by MengChenJack** [lkw199711/smanga#36]
目前默认的排序方式是按照入库时间来排序的，如果选择了其他排序方式（如按名称），一旦刷新或是关掉重开则又会被还原到默认排序方式。如果能使排序功能不会随着刷新而改变，或是允许用户设定默认排序方式，会更好一些。

**Comment by MengChenJack** [comment]
已收到，期待更新





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lkw199711/smanga"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月4日(星期二) 晚上8:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lkw199711/smanga] 希望能使排序功能持久化 (Issue #36)





 
此功能关联"个人设置"模块，预计将在下下个版本更新

**Comment by lkw199711** [comment]
3.2.2新增配置项
