### ISSUE TITLE
ios端 网页浏览有bug，无法看到登陆按键

### ISSUE THREAD

**Issue by ShaoyuWang1** [lkw199711/smanga#37]
在ios端访问“登陆键”会被遮挡住
![16541680589393_ pic](https://user-images.githubusercontent.com/40138256/229705507-6fdbf874-667c-4a3e-a268-7da77e56edde.jpg)

**Comment by lkw199711** [comment]
此问题将在下一版本得到临时性处理

**Comment by lkw199711** [comment]
![image](https://user-images.githubusercontent.com/38646029/230131922-c742631b-1ee2-4236-ad59-8f52f59c9c56.png)
beta(3.2.0) 版本, 默认登录在前, 点击下方卡片可以切换显示
