### ISSUE TITLE
EPUB文件无法正确识别封面

### ISSUE THREAD

**Issue by ShaoyuWang1** [lkw199711/smanga#38]
<img width="907" alt="image" src="https://user-images.githubusercontent.com/40138256/229705812-b5deccf5-2e21-44af-bbf0-61a2efc1d101.png">
看到对应的metadata进入docker挂载的poster文件夹内查看时发现所有的提取出的png文件均无法打开：
<img width="978" alt="image" src="https://user-images.githubusercontent.com/40138256/229706277-39098019-80a8-487c-8d6b-40ee25c56cd7.png">
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/40138256/229706493-fadd1372-0fe7-4eb9-b82d-830be9488162.png">

**Comment by lkw199711** [comment]
需要您的epub示例文件用于调试

**Comment by ShaoyuWang1** [comment]
sure, 但我检测发现几乎所有epub都有：
1） 封面无法检测
2）漫画内容显示是乱序的

（2）问题我用其他的docker漫画应用（lanraragi）也发现了，怀疑是解压后无法正确识别 image order导致的
[test.zip](https://github.com/lkw199711/smanga/files/11156329/test.zip)

**Comment by lkw199711** [comment]
![image](https://user-images.githubusercontent.com/38646029/235335367-4b8d548e-969d-4af6-8ac4-f31663cd72ae.png)
找到了问题所在，列表中混入了两个奇怪的名称html文件，由于第一个图片加载错误阻碍了之后的运行。是我的正则有问题，此问题将在下一个版本进行错误。感谢反馈

**Comment by lkw199711** [comment]
此问题于beta（3.2.4）版本修复
