### ISSUE TITLE
书签

### ISSUE THREAD

**Issue by 18ss** [lkw199711/smanga#47]
在瀑布浏览方式下，书签并没有生效，而且瀑布浏览方式下翻页有一点慢

**Comment by lkw199711** [comment]
由于浏览方式区别原因，书签功能不能在条漫模式下得到很好的支持，目前只是考虑到有合并十话以上的pdf文件，为了记录进度而制作，如能够大体记录到，就算是实现了。
如果有更好的技术和实现方式，将在后续版本进行进一步修正。感谢提交
