### ISSUE TITLE
[bug] 媒体库漫画浏览界面默认条数问题

### ISSUE THREAD

**Issue by fmd12345** [lkw199711/smanga#48]
bug描述：
使用最新的3.2.0版docker 
进入媒体库
进入漫画章节浏览界面
实际显示的章节条数为12条，但是下方的页面条数可选默认为20
然后点击第二页，再切回第一页，都会按照20条每页的章节数量进行显示
![image](https://user-images.githubusercontent.com/5960842/232324256-5947f3d5-640d-4574-bcd3-93b9581f2cc7.png)

**Comment by lkw199711** [comment]
此功能为不通尺寸的设备做兼容的bug，我准备在后续版本支持到个人设置模块，设置页面容量。此问题将在设置模块版本更新同时得到修正。感谢提交。
