### ISSUE TITLE
3.2.2左边的媒体库管理按钮不见了？

### ISSUE THREAD

**Issue by z14mian** [lkw199711/smanga#56]
![00](https://user-images.githubusercontent.com/18344479/234022698-ba712d97-38cf-4ea6-a8e0-402bb72ce868.png)

**Comment by lkw199711** [comment]
由于新增了权限管理功能，由老版本升级到3.1.6之后，老用户需要重新登录获得缓存。
将url地址栏路径换成/#/login，进入登录界面。重新登录即可。
此issues将关闭。
