### ISSUE TITLE
请问路径究竟应该怎么设

### ISSUE THREAD

**Issue by atiko00** [lkw199711/smanga#58]
我在docker的设置面板里已经制定了文件夹，但是在媒体库设置里输入此路径就是显示无法读取，请问到底应该怎么设置

**Comment by lkw199711** [comment]
无法读取路径两种情况，一是路径不存在，二是无权限读取。请确认文件夹已经777，然后路径映射正确。

**Comment by atiko00** [comment]
thx，我自己搞明白了
