### ISSUE TITLE
封面选择与评分

### ISSUE THREAD

**Issue by Zero-S0** [lkw199711/smanga#92]
1.能否自定义封面，因为有些漫画下载下来，第一页并不适合当封面。或者增加一个选项，在修改漫画内容后，可以手动仅仅更新该漫画内容或者更新所有漫画的封面。
2.添加标签系统，自己可以给漫画打标签，评分，从而使用标签和评分筛选内容(如果能够导入或者刮削外部网站就更好啦，如果存在风险的话，能不能通过预留接口，通过其它项目完成)。
![6666666666666](https://github.com/lkw199711/smanga/assets/84006919/da9bba27-95e2-442d-be26-13df4440bbfa)

最后，非常感谢大佬的努力，这个项目用起来很棒的。

**Comment by lkw199711** [comment]
1. 漫画封面设置在漫画设置中
 ![image](https://github.com/lkw199711/smanga/assets/38646029/8c44b966-3a0a-4ad1-888b-4011be5043e9)
2. 自动封面获取正在做
3. 标签系统后续会做

**Comment by Zero-S0** [comment]
> 1. 漫画封面设置在漫画设置中
>    ![image](https://user-images.githubusercontent.com/38646029/241605340-8c44b966-3a0a-4ad1-888b-4011be5043e9.png)
> 2. 自动封面获取正在做
> 3. 标签系统后续会做



> 1. 漫画封面设置在漫画设置中
>    ![image](https://user-images.githubusercontent.com/38646029/241605340-8c44b966-3a0a-4ad1-888b-4011be5043e9.png)
> 2. 自动封面获取正在做
> 3. 标签系统后续会做

1.我刚才尝试去寻找我需要修改的漫画，发现 漫画管理 功能中没有检索功能，无法快速找到想要修改的漫画。漫画管理 功能页面也无法进行排序。
2.是否可以考虑在漫画的阅读界面进行 漫画编辑 或者 设置封面 等功能。

**Comment by lkw199711** [comment]
好的

**Comment by lkw199711** [comment]
漫画管理 页面添加了检索功能,也新增了元数据扫描,展示作者 评分之类的信息,之后我会在readme文档中更新info.json的格式.
