### ISSUE TITLE
路径问题

### ISSUE THREAD

**Issue by colinwong92** [lkw199711/smanga#99]
能否支持局域网路径和中文路径？例如：192.168.2.1/share/comic；或者/share/漫画/

**Comment by lkw199711** [comment]
可以支持，但是注意群晖必须放在二级目录，一层识别不到

**Comment by lkw199711** [comment]
"192.168.2.1/share/comic"  明显为smb目录, smanga镜像不支持网络路径挂载, 请在系统层面挂载网络目录
